### ISSUE TITLE
Add shared-access to the read-group as well

### ISSUE THREAD

**Issue by gaetan-h** [cognitedata/inso-bootstrap-cli#33]
Could be done in 2 ways:
- Either by having an extra section like shared-read
- Giving read access to the :read groups from the shared-access list

I would tend to go for the second option to limit the expansion of the config yaml, but good to discuss
I think it would be quite beneficial to have this

**Comment by spex66** [comment]
By design-descision only `:owner` groups benefit from the `shared-access` support atm.

What's possible today is to use `:owner` groups a bit creative :)
You can create a namespace & nodes in the configuration, let's name them:
```
    - ns-name: read
      description: Use the created :owner groups to support shared-read access. The additional dataset with owner access, can be ignored
      ns-nodes:
        - node-name: read:001:case1
          description: Description about shared-read requirement
          shared-access:
            read:
              - node-name: src:001:sap
              - node-name: src:002:weather
```

-----
open to discuss another (smarter, more easier) support later. So let's keep this feature-request open as `backlog`
